### ISSUE TITLE
Resources to check

### ISSUE THREAD

**Issue by savchenko** [savchenko/windows#13]
https://malwaretips.com/threads/how-the-hell-wd-works-on-windows-home-pro.95146/page-3#post-836317

**Comment by beerisgood** [comment]
This is why I recommend the tool Hard_Configurator from @AndyFul as he know what he's doing.

Also the whole thread is good, not only one specific post. I add it to my hardening repository

**Comment by savchenko** [comment]
Closing as the historical artefact. Re-assessing what is going to happen with this repository.
